name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Decode GOOGLE_SERVICES_JSON secret
        run: echo "$GOOGLE_SERVICES_JSON" | base64 --decode > app/google-services.json
      - name: Build with Gradle
        run: ./gradlew build
