name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Create GOOGLE_SERVICES_JSON file
        run: cat /home/runner/work/PgnToGif/PgnToGif/app/google-services.json | base64
      - name: Decode GOOGLE_SERVICES_JSON secret
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 --decode > /home/runner/work/PgnToGif/PgnToGif/app/google-services.json
      - name: Build with Gradle
        run: ./gradlew build
